### PR TITLE
Forum upgrades

### PR DESCRIPTION
**Pull request by jayroh**
The latest version of the thredded gem has had a bunch of adjustments made and commited directly related to the Purple Door app. Thank you to @saturnflyer and the Purple Door project for helping tease out some of these tangled bits.

The biggest wins from the latest version include:
- Parts that had previously necessitated having configuration changes (mostly related to the asset pipeline) made in the parent app have been pushed down into the gem.
- "Theme" is no longer a thing with this gem. Sticking with Rails' default view path lookup is the better approach.
- Less dependencies. Carrierwave and fog are no longer dependencies so the memory usage should reduce significantly.
- Views and assets are now moved to the vendor directory, as they should. External gems should have all files copied over into the vendor dir so as not to mix with the main application.

### CODE REVIEW

**Comment by saturnflyer** [comment]
:tada: thanks @jayroh !

**Comment by saturnflyer** [comment]
@jayroh just got a deploy failure with:

```
Sass::SyntaxError: Undefined variable: "$helvetica".
/tmp/build_4b468656f83b5d4dc0a207e362df1829/saturnflyer-purple_door-18106b7/vendor/assets/stylesheets/thredded/base/_variables.scss:2
/tmp/build_4b468656f83b5d4dc0a207e362df1829/saturnflyer-purple_door-18106b7/vendor/assets/stylesheets/thredded/base/_base.scss:6
...
```

Does that look familiar?

**Comment by jayroh** [comment]
@saturnflyer it does. The only time I've seen that is when bourbon isn't in the Gemfile. When looking at the Gemfile here, however, it's obviously in there.

Wild guess - Try moving bourbon, neat, bitters up above thredded in the Gemfile and see if it's a load order thing. I've been testing here locally and things look fine so this is a totally weird one.

**Comment by jayroh** [comment]
@saturnflyer any news on that deploy? Did it get fixed w/a re-order of the gems?

**Comment by jcavena** [comment]
The last two builds failed. The last one was 5 hours ago. Still same issue.

**Comment by jayroh** [comment]
Hrmph. Will investigate further over here.

**Comment by jayroh** [comment]
Alright so I have a lead here and will have something before (around) EOD. According to the bourbon docs, and a lot of googling, using the require_tree directive in an asset manifest AND using bourbon are not the world's best match.

**Comment by saturnflyer** [comment]
Thanks for looking into it @jayroh. I didn't have time yesterday.
I would have expected the update to thredded to remove the need to add bourbon/neat/bitters to this Gemfile entirely since they are dependencies of thredded. I didn't play with it, but was surprised that we'd still need them.

I see that we are using `require_tree .` and in general I like to avoid it and to explicitly set the required files. So @jayroh are you saying that if we removed that then we might get around this problem? It might mean that purple_door can get past it, but I'm curious about how thredded should handle this.
Thanks so much for your help!

**Comment by jayroh** [comment]
@saturnflyer, no worries Jim. This was one totally on me and hell if I was going to make you dig through it all. Good news is, I figured it out :smile: 

First - the `require_tree` thing is something, like you, I tend to try and avoid at all costs so I went in and made some changes here to fix (for lack of a better word) that. Second - this entire problem was due to a greedy regex in the thredded gem's config that was attempting to precompile assets that looked anything like `thredded*(css|js)` ... turns out that was _also_ interpreting `thredded/*.css`  ... that's right, everything in the namespace dir was attempting to be precompiled as well. Hence, the issue.

I won't go into why that was originally there, but suffice it to say it was a premature optimization gone wrong.

End result - I DO have a fix here that will go up today when I can squeeze some time in to clean some things up and submit a proper PR.

**Comment by jayroh** [comment]
Also - any and all apologies are from me, to you guys - @saturnflyer @jcavena. Seriously, sorry for the snafu.

**Comment by jcavena** [comment]
Glad you found the problem! No need to apologize. Happy someone is working on this. I need to put in some time too!

**Pull request merged**
